### ISSUE TITLE
2.0.0 Builds

### ISSUE THREAD

**Issue by jpnielsen** [Bloodbat/SanguineMutants#1]
Built some plugins, as [requested](https://community.vcvrack.com/t/new-sanguine-modules-mutants-module/22071?u=jens.peter.nielsen).

[SanguineMutants-2.0.0-win-x64.zip](https://github.com/Bloodbat/SanguineMutants/files/15133375/SanguineMutants-2.0.0-win-x64.zip)
[SanguineMutants-2.0.0-lin-x64.zip](https://github.com/Bloodbat/SanguineMutants/files/15133376/SanguineMutants-2.0.0-lin-x64.zip)
[SanguineMutants-2.0.0-mac-x64.zip](https://github.com/Bloodbat/SanguineMutants/files/15133377/SanguineMutants-2.0.0-mac-x64.zip)
[SanguineMutants-2.0.0-mac-arm64.zip](https://github.com/Bloodbat/SanguineMutants/files/15133374/SanguineMutants-2.0.0-mac-arm64.zip)

**Comment by Bloodbat** [comment]
Thanks :)
