### ISSUE TITLE
Etesia crashes Reaper on project load (2.5.2 vcv pro)

### ISSUE THREAD

**Issue by Inhibitd** [Bloodbat/SanguineMutants#6]
I dont know if this is a buffer load issue or not, will not reload from recovery (crashes when vcv instance containing etesia is activated from fx panel too). The issue occurred in stretch mode

**Comment by Bloodbat** [comment]
Does this happen with Nebulae and Fluctus as well?

Does this happen using any other modes?

**Comment by Bloodbat** [comment]
This issue has been fixed in the 2.4.2 release or the Nightly builds.

The release can be found here:

https://github.com/Bloodbat/SanguineMutants/releases/tag/2.4.2

Or you can wait for it to drop in the Library.
