### ISSUE TITLE
A ByteBeats crash fix (maybe)

### ISSUE THREAD

**Issue by SteveRussell33** [Bloodbat/SanguineMutants#7]
When I was working on my version of this I initalised ``t_ = 0;`` in ``ByteBeats::Init`` this solved a couple of arithmetic exceptions.

https://github.com/Bloodbat/SanguineMutants/blob/8cf1094bccc6efa0ddcb3bf216707b007e645144/alt_firmware/deadman/number_station/deadman_bytebeats.cc#L89-L90

https://github.com/Bloodbat/SanguineMutants/blob/8cf1094bccc6efa0ddcb3bf216707b007e645144/alt_firmware/deadman/number_station/deadman_bytebeats.cc#L44-L50

**Comment by Bloodbat** [comment]
Thanks Steve :)
ByteBeats wasn't crashing anymore; but some equations didn't really produce interesting results.
I did initialize the vars as both you and Squinky suggest; but that didn't fix the crashes (I expected that); however, I applied the same treatment I used for Aestus and the crashes remain gone, at least in my tests, AND the results for most equations are more interesting, so, that's a win :)
